### ISSUE TITLE
need key to make search non-recursive

### ISSUE THREAD

**Issue by tbrowder** [tadzik/File-Find#20]

**Comment by tadzik** [comment]
You mean, not look inside directories at all? Would something like find(maxdepth => 1) be enough?

**Comment by jjatria** [comment]
I came here looking for the same, but when I looked at the code to try to implement it, I realised that the option is already there. It was added in e74767e26b0c.

I've just opened #30 to add `:recursive` to the documentation. That would definitely have saved me some trouble.

**Comment by lizmat** [comment]
Thanks for the effort!  PR merged, so closing issue!
